experiment:
  name: angles
  dataset: 
    tortosity:
      - moderate
    num_vessels_for_each: 1
    grid_angles: 
      min_angle: -180
      max_angle: 180
      step: 30
    SID: 1.2
    SOD: 0.8
    SPACING: 0.00035

  testcase:
    type: angles
    metrics:
      - dice
      - iou
      - chamfer
