experiment:
  name: general_clinical
  dataset: 
    tortosity:
      - simple
      - moderate
      - tortuous
    num_vessels_for_each: 200
    angle_pairs:
      - [-60, 30.0] # RAO 30, CRA 30
      - [-150, 30]  # LAO 60, CRA 30
      - [-60, -30]  # RAO 30, CAU 30
    SID: 1.2
    SOD: 0.8
    SPACING: 0.00035

  testcase:
    type: general
    metrics:
      - dice
      - iou
      - chamfer
      - dice2d
      - iou2d
