experiment:
  name: general_clinical
  dataset: 
    tortosity:
      - simple
      - moderate
      - tortuous
    num_vessels_for_each: 5
    angle_pairs:
      - [-130, 10]   # LAO 40
      - [-15, 10]  # LAO 20, Cranial 20
      - [-60, 0]    # RAO 30 
    SID: 1.2
    SOD: 0.8
    SPACING: 0.00035

  testcase:
    type: general
    metrics:
      - dice
      - iou
      - chamfer
      - dice2d
      - iou2d
