experiment:
  name: translations
  dataset: 
    tortosity:
      - moderate
    num_vessels_for_each: 1
    angle_pairs:
      - [0, 0]
      - [0, 90]
      - [90, 0]
    translation_xy_range: [-50, 50, 10]
    SID: 1.2
    SOD: 0.8
    SPACING: 0.00035
  testcase:
    type: noise
    metrics:
      - dice
      - iou
      - chamfer
      - dice2d
      - iou2d
